config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  namespace :admin do
    resources :users, only: [:create]
  end

  root to: "pages#home"
  get '/users/sign_out', to: 'sessions#destroy', as: :sign_out
  
  get "about", to: "pages#about", as: :about
  get "rsvp", to: "pages#rsvp", as: :rsvp
  get "program", to: "pages#program", as: :program
  
  # Remove the duplicate 'seating' route
  get "accomodation", to: "pages#accomodation", as: :accomodation
  get "travel", to: "pages#travel", as: :travel

  get "gift", to: "pages#gift", as: :gift
  get "svtd", to: "pages#svtd", as: :svtd

  get "guests", to: "guests#index"
  get "guests/:id", to: "guests#show"
  get "couples", to: "pages#couples"
  devise_scope :user do
    # Keep the 'seating' route within the users/registrations scope
    get 'seating', to: 'users/registrations#seating'
    put 'update_current_question', to: 'users/registrations#update_current_question'
    get 'hidden', to: 'users/registrations#hidden'
    post 'hidden', to: 'users/registrations#hidden'

    get 'hidden_questions', to: 'users/registrations#hidden_questions'
    post 'hidden_questions', to: 'users/registrations#hidden_questions'
    post 'update_questions', to: 'users/registrations#update_question', as: :update_question
    post 'create_question', to: 'users/registrations#create_question'
    delete 'questions/:id', to: 'users/registrations#destroy_question', as: :delete_question

    get 'reset_submission', to: 'users/registrations#reset_submission', as: 'reset_submission'
    patch 'users/:id', to: 'users/registrations#update2', as: :registration
    patch 'users/:id/reset_question', to: 'users/registrations#reset_question', as: :reset_question
    delete 'users/:id', to: 'users/registrations#destroy', as: :user_registration_destroy
    put 'users/:id/toggle_friday', to: 'users/registrations#toggle_friday', as: :user_registrations_togglefriday
    put 'users/:id/toggle_ceremony', to: 'users/registrations#toggle_ceremony', as: :user_registrations_toggleceremony

    put 'users/:id/answerfriday', to: 'users/registrations#answerfriday', as: :user_registrations_answerfriday
    put 'users/:id/answerceremony', to: 'users/registrations#answerceremony', as: :user_registrations_answerceremony
    put 'users/:id/answerreception', to: 'users/registrations#answerreception', as: :user_registrations_answerreception
    put 'users/:id/answerdinner', to: 'users/registrations#answerdinner', as: :user_registrations_answerdinner

    

  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<style>
  .navbar {
    background-color: #C8DCFF;
    color: #000000;
  }

  body {
    background-color: #b3d1ff;
  }

  /* Styles for larger screens */
  @media screen and (min-width: 577px) {
    .navbar-nav {
      display: flex; /* Use flexbox for the nav items */
      justify-content: space-between; /* Space between the groups */
      width: 100%; /* Full width to spread items */
      transition: display 0.5s ease; /* Smooth transition for the menu */
    }

    .nav-group {
      display: flex; /* Use flexbox for the group */
    }

    .navbar-nav .nav-item {
      margin: 0 5px; /* Adjust margins for spacing */
    }

    .navbar-nav .nav-link {
      font-size: larger;
      padding: 10px;
      color: #6B2527; /* Normal font color */
      text-decoration: none; /* Optional: Removes underline from links */
    }

    .navbar-nav .nav-link:hover {
      color: #ce7c3f; /* Hover font color */
    }
  }
.hamburger-icon {
  display: none;
  cursor: pointer;
  padding: 10px;
  border: none;
  background: transparent;
}

.hamburger-line {
  display: block;
  width: 25px; /* Width of the line */
  height: 3px; /* Height of the line */
  background-color: #6B2527; /* Color of the line */
  margin: 5px 0; /* Spacing between lines */
}
  /* Styles for smaller screens */
@media screen and (max-width: 576px) {
  .navbar-collapse {
    display: none;
    text-align: left; /* Aligns text to the left */
  }

  /* Show the hamburger icon on small screens */
  .hamburger-icon {
    display: block;
  }
    .navbar-nav {
    width: 100%; /* Ensures the navbar takes full width */
  }

  .navbar-nav ul {
    padding-left: 0; /* Removes padding to align items to the edge */
  }

  .nav-item {
    text-align: left; /* Aligns the text of nav items to the left */
  }
}
</style>




<% if @phase == 1 %>
  <nav class="navbar navbar-expand-sm navbar-light">
    <button class="hamburger-icon" onclick="toggleMenu()">
  <span class="hamburger-line"></span>
  <span class="hamburger-line"></span>
  <span class="hamburger-line"></span>
    </button>

    <div class="container-fluid">
      <% if user_signed_in? %>
        <div class="navbar-nav">
          <div class="nav-group">
            <%= link_to "Home", root_path, class: "nav-link nav-item" %>
            <%= link_to "Where is this thing happening?", travel_path, class: "nav-link nav-item" %>
          </div>
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link nav-item" %>
        </div>
      <% end %>
    </div>
  </nav>
<% end %>
<%if @phase ==2%>
<nav class="navbar navbar-expand-sm navbar-light">
      <button class="hamburger-icon" onclick="toggleMenu()">
  <span class="hamburger-line"></span>
  <span class="hamburger-line"></span>
  <span class="hamburger-line"></span>
    </button>
  <div class="container-fluid">

    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav w-100">
        <% if user_signed_in? %>
          <li class="nav-item mr-auto">
            <%= link_to "The Wedding/RSVP", root_path, class: "nav-link", id: "wedding-rsvp-link" %>
          </li>     
          <li class="nav-item mx-auto">
            <%= link_to "Travel/Accommodation", travel_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-auto">
            <%= link_to "Gifts/Registry", "https://www.kadolog.com/en/list/livia-matthieu-25-05-24-479585", target: "_blank", class: "nav-link" %>
          </li>
          <li class="nav-item mx-auto">
            <%= link_to "Table Seatings", seating_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-auto">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

<%end%>

<script>
function toggleMenu() {
  var nav = document.querySelector('.navbar-collapse'); // Adjusted to target .navbar-collapse
  if (nav.style.display === "block") {
    nav.style.display = "none";
  } else {
    nav.style.display = "block";
  }
}

// Add event listener for the wedding RSVP link
document.addEventListener('DOMContentLoaded', function() {
  var weddingRsvpLink = document.getElementById('wedding-rsvp-link');
  if (weddingRsvpLink) {
    weddingRsvpLink.addEventListener('click', function(e) {
      e.preventDefault(); // Prevent the default link behavior
      // Navigate to the link with a unique timestamp query parameter to ensure a fresh page load
      window.location.href = this.href + '?t=' + new Date().getTime();
    });
  }
});
</script>