config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  namespace :admin do
    resources :users, only: [:create]
  end

  root to: "pages#home"
  get '/users/sign_out', to: 'sessions#destroy', as: :sign_out
  
  get "about", to: "pages#about", as: :about
  get "rsvp", to: "pages#rsvp", as: :rsvp
  get "program", to: "pages#program", as: :program
  
  # Remove the duplicate 'seating' route
  get "accomodation", to: "pages#accomodation", as: :accomodation
  get "travel", to: "pages#travel", as: :travel

  get "gift", to: "pages#gift", as: :gift
  get "svtd", to: "pages#svtd", as: :svtd

  get "guests", to: "guests#index"
  get "guests/:id", to: "guests#show"
  get "couples", to: "pages#couples"
  devise_scope :user do
    # Keep the 'seating' route within the users/registrations scope
    get 'seating', to: 'users/registrations#seating'
    put 'update_current_question', to: 'users/registrations#update_current_question'
    get 'hidden', to: 'users/registrations#hidden'
    post 'hidden', to: 'users/registrations#hidden'

    get 'hidden_questions', to: 'users/registrations#hidden_questions'
    post 'hidden_questions', to: 'users/registrations#hidden_questions'
    post 'update_questions', to: 'users/registrations#update_question', as: :update_question
    post 'create_question', to: 'users/registrations#create_question'
    delete 'questions/:id', to: 'users/registrations#destroy_question', as: :delete_question

    get 'reset_submission', to: 'users/registrations#reset_submission', as: 'reset_submission'
    patch 'users/:id', to: 'users/registrations#update2', as: :registration
    patch 'users/:id/reset_question', to: 'users/registrations#reset_question', as: :reset_question
    delete 'users/:id', to: 'users/registrations#destroy', as: :user_registration_destroy
    put 'users/:id/toggle_friday', to: 'users/registrations#toggle_friday', as: :user_registrations_togglefriday
    put 'users/:id/toggle_ceremony', to: 'users/registrations#toggle_ceremony', as: :user_registrations_toggleceremony

    put 'users/:id/answerfriday', to: 'users/registrations#answerfriday', as: :user_registrations_answerfriday
    put 'users/:id/answerceremony', to: 'users/registrations#answerceremony', as: :user_registrations_answerceremony
    put 'users/:id/answerreception', to: 'users/registrations#answerreception', as: :user_registrations_answerreception
    put 'users/:id/answerdinner', to: 'users/registrations#answerdinner', as: :user_registrations_answerdinner

    

  end
end

app/views/pages/about.html.erb
<%= render "shared/navbar" %>

app/views/pages/accomodation.html.erb
<style>

</style>

<% @phase = current_user&.phase || 2 %>
    <%= render "shared/navbar" %>
    <h1>
        Where to sleep
    <h1>

app/views/pages/couples.erb
<%= @text%>

app/views/pages/gift.html.erb
<style>

</style>

<% @phase = current_user&.phase || 2 %>
    <%= render "shared/navbar" %>
    <h1>
        What to give us
    <h1>

app/views/pages/hidden.html.erb
<style>
.custom-badge {
    background-color: green;
    color: white;
    padding: 5px;
    border-radius: 5px;
}
.badge-margin {
    margin: 5px; /* Adjust the value as needed */
}
</style>


<% @phase = current_user&.phase || 2 %>
    <%= render "shared/navbar" %>
<div class="container">
    <!-- Registration Form Section -->
    <div class="row">
      <!-- Registration Form Section -->
      <div class="col-md-6">
        <h2 class="text-center">Sign up new Invites</h2>

        <%= simple_form_for(@new_user, url: hidden_path, method: :post) do |f| %>
          <%= f.error_notification %>

          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.input :email, required: true, autofocus: true, input_html: { autocomplete: "email" }, label: false, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.input :password, required: true, hint: " Minimum 6 characters", input_html: { autocomplete: "new-password" }, label: false, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'Password Confirmation' %>
            <%= f.input :password_confirmation, required: true, input_html: { autocomplete: "new-password" }, label: false, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.input :name, required: true, input_html: { autocomplete: "name" }, label: false, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :personal_message_us, 'Our personnal message?' %>
            <%= f.input :personal_message_us, required: false, input_html: { autocomplete: "personal_message_us" }, label: false, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :vip, 'vip?' %>
            <%= f.input :vip, required: false, input_html: { autocomplete: "vip" }, label: false, class: "form-control" %>
          </div>
          <div class="form-check">
            <%= f.check_box :is_admin, class: "form-check-input" %>
            <%= f.label :is_admin, class: "form-check-label" %>
          </div>



          <div class="form-group mt-3">
            <%= f.button :submit, "Sign up", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>


    <!-- Invitees List Section -->
<!-- Invitees List Section -->
<div class="col-md-6">
  <h2 class="text-center">Invitees List</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th>Answered Save the date?</th>
        <th>invited Friday</th>
        <th>invited to Ceremony</th>
        <th>Answer friday?</th>
        <th>Answer ceremony?</th>
        <th>Answer reception?</th>
        <th>Answer dinner?</th>
        <th>Answer the invition?</th>

        <th>Dietary Restriction</th>
        <th>Plus ones?</th>
        <th>Reset Seating</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
   <% @users.each do |user| %>
   <% has_answered = user.answer_friday == 'yes' ||user.answer_ceremony == 'yes' || user.answer_reception == 'yes' || user.answer_diner == 'yes' %>

    <tr>
      
      <td>
      <!-- Toggle Edit Form Button -->
        <button onclick="toggleEditForm(<%= user.id %>)">
        <%= user.email %>
        </button>
        <!-- Reset Question Button -->
      </td>
      
      <td>
        <!-- Display 'Has Answered' if the address is not empty -->
        <% if user.address.present? %>
          <span class="custom-badge badge-margin">Answered</span>
        <% end %>
      </td>

      <td>
        <%= button_to user.friday, user_registrations_togglefriday_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "friday-button-#{user.id}" %>
      </td>
      <td>
        <%= button_to user.ceremony, user_registrations_toggleceremony_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "ceremony-button-#{user.id}" %>
      </td>

      <% if !has_answered %>
      <td>
        <%= button_to user.answer_friday, user_registrations_answerfriday_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "friday_answer-button-#{user.id}" %>
      </td>
      <td>
        <%= button_to user.answer_ceremony, user_registrations_answerceremony_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "ceremony_answer-button-#{user.id}" %>
      </td>
      <td>
        <%= button_to user.answer_reception, user_registrations_answerreception_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "reception_answer-button-#{user.id}" %>
      </td>
      <td>
        <%= button_to user.answer_diner, user_registrations_answerdinner_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "dinner_answer-button-#{user.id}" %>
      </td>
      
      <% else %>
      <td>
        <%= button_to user.answer_friday, user_registrations_answerfriday_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "friday_answer-button-#{user.id}", style: "background-color: green;"%>
      </td>
      <td>
        <%= button_to user.answer_ceremony, user_registrations_answerceremony_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "ceremony_answer-button-#{user.id}" , style: "background-color: green;"%>
      </td>
      <td>
        <%= button_to user.answer_reception, user_registrations_answerreception_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "reception_answer-button-#{user.id}" , style: "background-color: green;"%>
      </td>
      <td>
        <%= button_to user.answer_diner, user_registrations_answerdinner_path(user), method: :put, remote: true, class: "btn btn-sm btn-toggle", id: "dinner_answer-button-#{user.id}" , style: "background-color: green;"%>
      </td>
      <% end %>
      <% if user.has_answered_form == 'yes' %>
          <td><span class="custom-badge badge-margin"><%= user.has_answered_form %></span></td>
      <% else %>
          <td><%= user.has_answered_form %></td>
      <% end %>
            
      <td><%= user.dietary_restriction %></td>
      <td><%= user.plusones %></td>
      <td>
      <!-- Toggle Edit Form Button -->
        <%= form_with url: reset_question_path(user), method: :patch do %>
          <%= submit_tag 'Reset', class: 'btn btn-warning' %>
        <% end %>
      </td>
      <td>
      <!-- Delete Button -->
        <%= form_with url: user_registration_destroy_path(user), method: :delete do %>
          <%= submit_tag 'Delete', class: 'btn btn-danger', id: "delete-button-#{user.id}" %>
        <% end %>
      </td>
    </tr>
    <tr id="editForm<%= user.id %>" style="display:none;">
      <td colspan="5">
      <%= simple_form_for(user, url: registration_path(user), method: :patch) do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Title' %>
          <%= f.input :title, required: true, label: false, input_html: { value: user.title, class: "form-control", id: "user_title_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.input :name, required: true, label: false, input_html: { value: user.name, class: "form-control", id: "user_name_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :family_name, 'Family name' %>
          <%= f.input :family_name, required: true, label: false, input_html: { value: user.family_name, class: "form-control", id: "user_family_name_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :address, 'Address' %>
          <%= f.input :address, required: true, label: false, input_html: { value: user.address, class: "form-control", id: "user_address_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :pays, 'Country' %>
          <%= f.input :pays, required: true, label: false, input_html: { value: user.pays, class: "form-control", id: "user_pays_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :city, 'City' %>
          <%= f.input :city, required: true, label: false, input_html: { value: user.city, class: "form-control", id: "user_city_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :apartment, 'Apartment' %>
          <%= f.input :apartment, required: true, label: false, input_html: { value: user.apartment, class: "form-control", id: "user_apartment_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :postal_code, 'Postal Code' %>
          <%= f.input :postal_code, required: true, label: false, input_html: { value: user.postal_code, class: "form-control", id: "user_postal_code_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :personal_message_us, 'Our Personal Message' %>
          <%= f.input :personal_message_us, required: true, label: false, input_html: { value: user.personal_message_us, class: "form-control", id: "user_personal_message_us_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :personal_message_them, 'Their Personal Message' %>
          <%= f.input :personal_message_them, required: true, label: false, input_html: { value: user.personal_message_them, class: "form-control", id: "user_personal_message_them_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :ceremony, 'Ceremony' %>
          <%= f.input :ceremony, label: false, input_html: { value: user.ceremony, class: "form-control", id: "user_ceremony_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :friday, 'Friday' %>
          <%= f.input :friday, label: false, input_html: { value: user.friday, class: "form-control", id: "user_friday_#{user.id}" } %>
        </div>
        <div class="form-group">
          <%= f.label :dietary_restriction, 'Dietary Restriction' %>
          <%= f.input :dietary_restriction, label: false, input_html: { value: user.dietary_restriction, class: "form-control", id: "user_dietary_restriction_#{user.id}" } %>
        </div>

        <div class="form-group">
          <%= f.label :plusones, 'Plus ones' %>
          <%= f.input :plusones, label: false, input_html: { value: user.plusones, class: "form-control", id: "plusones_#{user.id}" } %>
        </div>

        <div class="form-group">
          <%= f.label :phase, 'phase' %>
          <%= f.input :phase, required: true, label: false, input_html: { value: user.phase, class: "form-control", id: "user_phase_#{user.id}" } %>
        </div>

        <div class="form-group">
          <%= f.label :is_admin, 'Role' %>
          <%= f.select :is_admin, [['Admin', true], ['User', false]], { selected: user.is_admin, include_blank: false, label: false }, { class: "form-control", id: "user_is_admin_#{user.id}" } %>
        </div>

          <div class="form-group mt-3">
            <%= f.button :submit, "Save Changes", class: "btn btn-primary" %>
          </div>
        <% end %>


    </td>
  </tr>
<% end %>


<script>
  function toggleEditForm(userId) {
    var form = document.getElementById('editForm' + userId);
    form.style.display = form.style.display === 'none' ? '' : 'none';
  }
  document.addEventListener('DOMContentLoaded', function() {
  const deleteButtons = document.querySelectorAll('[id^="delete-button-"]');

  deleteButtons.forEach(button => {
    button.addEventListener('click', function(event) {
      event.preventDefault();
      const userId = this.id.replace('delete-button-', '');
      const confirmed = confirm('Are you sure you want to delete this user?');

      if (confirmed) {
        const form = this.closest('form');
        form.submit();
      }
    });
  });
});

var button = document.querySelector('#ceremony-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.ceremony %>';

var button = document.querySelector('#friday-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.friday %>';

var button = document.querySelector('#friday_answer-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.answer_friday %>';

var button = document.querySelector('#ceremony_answer-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.answer_ceremony %>';
var button = document.querySelector('#reception_answer-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.answer_reception %>';

var button = document.querySelector('#dinner_answer-button-<%= @user.id %>');
// Update the button text based on the new status
button.textContent = '<%= @user.answer_diner %>';
</script>

app/views/pages/hidden_questions.html.erb
<%= render "shared/navbar" %>

<!-- Begin table structure -->
<table class="table">
  <thead>
    <tr>
      <th>Order Number</th>
      <th>Question Text</th>
      <th>Options</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <!-- Edit existing questions form -->
    <%= form_tag(update_question_path, method: :post, id: "question-form") do %>
      <% @questions.each do |question| %>
        <tr>
          <td>
            <%= number_field_tag "questions[][order_nr]", question.order_nr, min: 0 %>
          </td>
          <td>
            <%= hidden_field_tag "questions[][id]", question.id %>
            <%= text_field_tag "questions[][question_text]", question.question_text %>
          </td>
          <td>
            <% question.options.each_with_index do |option, index| %>
              <%= text_field_tag "questions[][options][]", option, id: "question_#{question.id}_option_#{index}" %>
            <% end %>
            <!-- Placeholder for adding new options -->
            <%= text_field_tag "questions[][options][]", nil, placeholder: 'Add option', class: 'option-field' %>
          </td>
          <td>
            <%= button_tag type: 'button', class: 'btn btn-danger delete-question-form', data: { confirm: "Are you sure?", url: delete_question_path(question) } do %>
              <i class="fas fa-times"></i> <!-- Icon for delete action -->
            <% end %>
          </td>
        </tr>
      <% end %>
      <!-- Save changes button -->
      <tr>
        <td colspan="4">
          <%= submit_tag "Save Changes", class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>

    <!-- Add new question form -->
    <%= form_tag(create_question_path, method: :post, id: "new-question-form") do %>
      <tr>
        <td colspan="2">
          <%= text_field_tag "new_question[question_text]", nil, placeholder: 'Enter new question' %>
        </td>
        <td>
          <% 5.times do |index| %>
            <%= text_field_tag "new_question[options][]", nil, placeholder: "Option #{index + 1}", id: "new_question_option_#{index}" %>
          <% end %>
        </td>
        <td>
          <%= submit_tag "Add New Question", class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.delete-question-form').forEach(function(button) {
      button.addEventListener('click', function() {
        if (confirm(this.dataset.confirm)) {
          fetch(this.dataset.url, {
            method: 'DELETE',
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
            },
            credentials: 'same-origin'
          });
        }
      });
    });
  });
</script>

app/views/pages/program.html.erb
<style>

</style>

<% @phase = current_user&.phase || 2 %>
    <%= render "shared/navbar" %>
    <h1>
        Here is what we will do
    <h1>

app/views/pages/rsvp.html.erb
<style>

</style>

<% @phase = current_user&.phase || 2 %>
    <%= render "shared/navbar" %>
<div class="savethedateform">
    <%= form_for(current_user, url: user_registration_path, method: :patch) do |f| %>
      <div class="form-group">
        <%= f.label :title, 'Title:', class: 'control-label' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :name, 'Name:', class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :family_name, 'Family Name:', class: 'control-label' %>
        <%= f.text_field :family_name, class: 'form-control' %>
      </div>


      <div class="form-group">
        <%= f.label :address, 'Address and Street Number:', class: 'control-label' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :apartment, 'Apartment:', class: 'control-label' %>
        <%= f.text_field :apartment, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :postal_code, 'Postal Code:', class: 'control-label' %>
        <%= f.text_field :postal_code, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :city, 'City:', class: 'control-label' %>
        <%= f.text_field :city, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :pays, 'Country:', class: 'control-label' %>
        <%= f.text_field :pays, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :personal_message_them, 'Personal Message for Us?', class: 'control-label' %>
        <%= f.text_area :personal_message_them, class: 'form-control' %>
      </div>
      <div class="form-actions">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

app/views/pages/seating.html.erb
<style>
  .clickable-image-container {
    width: 200px; /* Default width */
    height: 200px; /* Default height */
    overflow: hidden;
    margin: 10px;
    padding: 20px;
  }

  .clickable-image {
    width: 100%;
    height: 100%;
    object-fit: contain;
    transition: transform 0.2s;
  }

  .clickable-image:hover {
    transform: scale(1.1);
    cursor: pointer;
  }

  .center-container, .center-text {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin: auto;
    margin-top: 50vh;
  }

  .center-container {
    transform: translateY(-90%);
  }

  .image-row {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }
  .center-container, .center-text {
    /* Existing styles */
    padding-top: 60px; /* Add padding to ensure content starts below the navbar */
    margin-top: 0; /* Adjust if necessary to balance the added padding */
    transform: translateY(0%); /* Adjust or remove as needed to align content */
  }

  
  /* Media query for screens narrower than 768px */
  @media (max-width: 768px) {
    .clickable-image-container {
      width: 100px; /* Smaller width */
      height: 100px; /* Smaller height */
      padding: 5px; /* Adjusted padding */
    }
  .image-row {
    flex-wrap: wrap; /* Allow items to wrap to the next line as needed */
    justify-content: center; /* Keep items centered */
  }
    .center-container, .center-text {
      margin-top: 20vh; /* Adjusted for smaller screens */
      transform: translateY(-50%); /* Adjust translateY for .center-container */
    }
  .center-container, .center-text {
    margin-top: 20vh; /* Adjusted for smaller screens */
    transform: translateY(-50%);
  }

    /* Optionally adjust font sizes */
    h1 {
      font-size: 20px; /* Smaller font size for headings */
    }

    p {
      font-size: 14px; /* Smaller font size for paragraphs */
    }
  }
</style>

<% @phase = current_user&.phase || 1 %>
<%= render "shared/navbar" %>

<% if @question.order_nr == 11 %>

<div class="center-text">
  <h1>Whouhouw, you answered everything!</h1>
  <br>
  <h1>We are so looking forward to party with you!</h1>
<div>
<% else %>
<div class="center-container">
  <p>Hello <%= @user.name %>! Let's play a game to decide on your seating during dinner based on your answers.</p>
  <h1><%= raw @question.question_text %></h1>
  <%= form_tag(update_current_question_path, method: :put, id: 'question-form') do %>
    <div class="image-row">
      <% @question.options.each do |option| %>
        <div class="clickable-image-container">
          <%= image_tag option, class: 'option-image img-fluid rounded clickable-image', data: { value: option } %>
          <%= radio_button_tag :selected_option, option, class: 'option-radio', style: 'display:none;' %>
        </div>
      <% end %>
    </div>

    <%= hidden_field_tag :question_id, @question.order_nr %>
  <% end %>
</div>

  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    $(document).ready(function() {
      $('.clickable-image').on('click', function() {
        $(this).siblings('.option-radio').prop('checked', true).trigger('click');
        $('#question-form').submit();
      });
    });
  </script>
<% end %>

app/views/pages/svtd.html.erb
<%= render "shared/navbar" %>